import type { MenuCategoryInterface } from "@/features";

export const getMenuService = async (): Promise<MenuCategoryInterface[]> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          id: "cat-1",
          type: "ENTRADAS",
          name: "Entradas",
          items: [
            {
              id: "1",
              name: "Rollitos primavera",
              description: "Crujientes rollos rellenos de vegetales",
              price: 12000,
              image: "https://i.blogs.es/40e6e2/rollitos_primavera/840_560.jpg",
              category: "ENTRADAS",
            },
            {
              id: "2",
              name: "Gyozas de cerdo",
              description: "Empanadillas japonesas a la plancha",
              price: 15000,
              image: "https://jetextramar.com/wp-content/uploads/2022/07/receta-de-gyozas-de-cerdo.jpg",
              category: "ENTRADAS",
            },
            {
              id: "3",
              name: "Edamame",
              description: "Vainas de soya al vapor con sal marina",
              price: 10000,
              image: "https://images.services.kitchenstories.io/P35ZhSf7mNJW3ntmAmX57XxtMEM=/3840x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R2958-final-photo-.jpg",
              category: "ENTRADAS",
            },
            {
              id: "4",
              name: "Bao buns",
              description: "Pan al vapor relleno de cerdo o pollo",
              price: 16000,
              image: "https://eatlittlebird.com/wp-content/uploads/2022/09/korean-fried-chicken-bao-buns-5.jpg",
              category: "ENTRADAS",
            },
          ],
        },
        {
          id: "cat-2",
          type: "SUSHI",
          name: "Sushi y Sashimi",
          items: [
            {
              id: "5",
              name: "California Roll",
              description: "Cangrejo, aguacate y pepino",
              price: 18000,
              image: "https://www.mashed.com/img/gallery/easy-california-roll-recipe/l-intro-1656513015.jpg",
              category: "SUSHI",
            },
            {
              id: "6",
              name: "Dragon Roll",
              description: "Anguila, aguacate y salsa dulce",
              price: 24000,
              image: "https://thesushiman.com/wp-content/uploads/2025/01/Dragon-Roll-1-scaled.jpg",
              category: "SUSHI",
            },
            {
              id: "7",
              name: "Philadelphia Roll",
              description: "Salmón, queso crema y aguacate",
              price: 20000,
              image: "https://thesushiman.com/wp-content/uploads/2025/01/Philadelphia-Roll-Edited2-scaled.jpg",
              category: "SUSHI",
            },
            {
              id: "8",
              name: "Sashimi de salmón",
              description: "Cortes frescos de salmón",
              price: 26000,
              image: "https://imag.bonviveur.com/presentacion-principal-del-sashimi-de-salmon.jpg",
              category: "SUSHI",
            },
          ],
        },
        {
          id: "cat-3",
          type: "SOPAS",
          name: "Sopas",
          items: [
            {
              id: "9",
              name: "Ramen de cerdo",
              description: "Caldo intenso con fideos, cerdo y huevo",
              price: 28000,
              image: "https://www.lanacion.com.ar/resizer/v2/a-shoyu-ramen-in-gray-bowl-on-concrete-table-top-3CCBARMPDRFI5O6H5OPS3PP66E.jpg?auth=5f4d38a8750849d33b7c6e6cd4aec32bcd639658006140e82c66d27189a3ca47&width=420&height=280&quality=70&smart=true",
              category: "SOPAS",
            },
            {
              id: "10",
              name: "Sopa miso",
              description: "Caldo ligero con tofu, algas y cebollín",
              price: 12000,
              image: "https://assets.tmecosys.com/image/upload/t_web_rdp_recipe_584x480_1_5x/img/recipe/ras/Assets/5509FCCF-6EB8-418B-99CF-D7EF5567682D/Derivates/0A82C349-F495-47C3-BDE2-E805C70F137E.jpg",
              category: "SOPAS",
            },
            {
              id: "11",
              name: "Udon",
              description: "Fideos gruesos en caldo caliente",
              price: 22000,
              image: "https://asianorigins.es/recetas/wp-content/uploads/2024/08/YAKI-UDON-CON-CERDO-Y-VERDURAS-FOTO-4-scaled.jpeg",
              category: "SOPAS",
            },
          ],
        },
        {
          id: "cat-4",
          type: "PLATOS",
          name: "Platos fuertes",
          items: [
            {
              id: "12",
              name: "Arroz frito",
              description: "Arroz salteado con vegetales y proteína",
              price: 18000,
              image: "https://i.blogs.es/8424ac/arroz-frito-chino/1200_900.jpg",
              category: "PLATOS",
            },
            {
              id: "13",
              name: "Pollo teriyaki",
              description: "Pollo a la parrilla con salsa teriyaki",
              price: 26000,
              image: "https://imag.bonviveur.com/pollo-en-salsa-teriyaki.jpg",
              category: "PLATOS",
            },
            {
              id: "14",
              name: "Pad Thai",
              description: "Fideos de arroz salteados estilo tailandés",
              price: 27000,
              image: "https://thai-foodie.com/wp-content/uploads/2025/08/plated-gluten-free-pad-thai.jpg",
              category: "PLATOS",
            },
            {
              id: "15",
              name: "Bowl de salmón",
              description: "Salmón, arroz y vegetales frescos",
              price: 30000,
              image: "https://imag.bonviveur.com/poke-bowl-de-salmon-recien-hecho.jpg",
              category: "PLATOS",
            },
          ],
        },
        {
          id: "cat-5",
          type: "TEMPURA",
          name: "Tempura",
          items: [
            {
              id: "16",
              name: "Camarones tempura",
              description: "Camarones rebozados y crujientes",
              price: 26000,
              image: "https://assets.tmecosys.com/image/upload/t_web_rdp_recipe_584x480/img/recipe/ras/Assets/33A50401-D4DA-452F-AD42-DC47F8E7C567/Derivates/77b9a339-6aa3-4454-8277-15f674dc63c3.jpg",
              category: "TEMPURA",
            },
            {
              id: "17",
              name: "Vegetales tempura",
              description: "Verduras fritas en masa ligera",
              price: 18000,
              image: "https://harineraelmolino.com/wp-content/uploads/2025/05/flat-lay-of-japanese-vegetable-tempura-recipe-with-ginger-ponzu-sauce.jpg",
              category: "TEMPURA",
            },
          ],
        },
        {
          id: "cat-6",
          type: "VEGETARIANO",
          name: "Vegetariano",
          items: [
            {
              id: "18",
              name: "Tofu teriyaki",
              description: "Tofu salteado con salsa dulce",
              price: 20000,
              image: "https://fullofplants.com/wp-content/uploads/2023/07/easy-vegan-air-fryer-teriyaki-tofu-thumb-2.jpg",
              category: "VEGETARIANO",
            },
            {
              id: "19",
              name: "Roll vegetariano",
              description: "Sushi con vegetales frescos",
              price: 16000,
              image: "https://veganos.madrid/wp-content/uploads/2023/01/sushi-vegano.jpg",
              category: "VEGETARIANO",
            },
          ],
        },
        {
          id: "cat-7",
          type: "BEBIDAS",
          name: "Bebidas",
          items: [
            {
              id: "20",
              name: "Té verde",
              description: "Té tradicional japonés",
              price: 6000,
              image: "https://www.recetas-japonesas.com/base/stock/Recipe/te-verde/te-verde_web.jpg.webp",
              category: "BEBIDAS",
            },
            {
              id: "21",
              name: "Limonada",
              description: "Refrescante bebida natural",
              price: 7000,
              image: "https://cdn0.celebritax.com/sites/default/files/styles/rectangle_blur_1200x900/public/recetas/limonada.jpg",
              category: "BEBIDAS",
            },
            {
              id: "22",
              name: "Soda japonesa",
              description: "Bebida gaseosa importada",
              price: 9000,
              image: "https://instagram.fbog19-1.fna.fbcdn.net/v/t51.82787-15/625575967_18315054991270808_3740798322130529579_n.jpg?stp=dst-jpg_e35_tt6&_nc_cat=105&ig_cache_key=MzgyMzI0ODc2NzYzODc1OTk1Mw%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6InhwaWRzLjE0NDB4MTIwMC5zZHIuQzMifQ%3D%3D&_nc_ohc=AhQLrLgjrRwQ7kNvwEt3dWo&_nc_oc=AdoEZjAFlAEWHnT5o3CChqA2QtzK-D487IyXYZKWYMJG4CYKknYTtXky6Yi6fxeJvyM&_nc_ad=z-m&_nc_cid=0&_nc_zt=23&_nc_ht=instagram.fbog19-1.fna&_nc_gid=M0XyhGkLsXtp-LcaNpRNKQ&_nc_ss=7a32e&oh=00_AfxFsbOqYPonqAqClktFGQ3upvudbWY6b28_zioOOZFU1Q&oe=69C67A75",
              category: "BEBIDAS",
            },
          ],
        },
        {
          id: "cat-8",
          type: "POSTRES",
          name: "Postres",
          items: [
            {
              id: "23",
              name: "Mochi",
              description: "Dulce japonés de arroz relleno",
              price: 10000,
              image: "https://i.blogs.es/ec22c4/mochis/1200_900.jpg",
              category: "POSTRES",
            },
            {
              id: "24",
              name: "Helado tempura",
              description: "Helado frito crujiente",
              price: 14000,
              image: "https://sushicentral.mx/wp-content/uploads/2023/07/helado-tempura.jpg",
              category: "POSTRES",
            },
          ],
        },
      ]);
    }, 500);
  });
};